#!/usr/bin/env python3
"""Validate or update the generated Swift animation contract."""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
CONTRACT_PATH = ROOT / "docs" / "pet-animation-contract.json"
GENERATED_SWIFT_PATH = ROOT / "Sources" / "LightPetDesktop" / "Core" / "GeneratedAnimationContract.swift"


def fail(message: str) -> None:
    print(f"error: {message}", file=sys.stderr)
    raise SystemExit(1)


def positive_int(payload: dict[str, Any], key: str) -> int:
    value = payload.get(key)
    if not isinstance(value, int) or value <= 0:
        fail(f"{key} must be a positive integer")
    return value


def nonnegative_int(payload: dict[str, Any], key: str) -> int:
    value = payload.get(key)
    if not isinstance(value, int) or value < 0:
        fail(f"{key} must be a non-negative integer")
    return value


def load_contract() -> dict[str, Any]:
    try:
        contract = json.loads(CONTRACT_PATH.read_text(encoding="utf-8"))
    except OSError as exc:
        fail(f"could not read animation contract: {exc}")
    except json.JSONDecodeError as exc:
        fail(f"animation contract is not valid JSON: {exc}")

    if not isinstance(contract, dict):
        fail("animation contract must be a JSON object")

    atlas = contract.get("atlas")
    states = contract.get("states")
    if not isinstance(atlas, dict):
        fail("animation contract is missing atlas")
    if not isinstance(states, list) or not states:
        fail("animation contract must contain states")

    columns = positive_int(atlas, "columns")
    rows = positive_int(atlas, "rows")
    positive_int(atlas, "cellWidth")
    positive_int(atlas, "cellHeight")
    nonnegative_int(atlas, "visibleAlphaThreshold")

    seen_states: set[str] = set()
    seen_rows: set[int] = set()
    for state_payload in states:
        if not isinstance(state_payload, dict):
            fail("each state must be a JSON object")
        state = state_payload.get("state")
        if not isinstance(state, str) or not state:
            fail("each state must have a non-empty state")
        if state in seen_states:
            fail(f"duplicate state: {state}")
        seen_states.add(state)

        row = nonnegative_int(state_payload, "row")
        if row >= rows:
            fail(f"{state} row {row} is outside atlas rows")
        if row in seen_rows:
            fail(f"duplicate atlas row: {row}")
        seen_rows.add(row)

        frame_count = positive_int(state_payload, "frames")
        if frame_count > columns:
            fail(f"{state} uses {frame_count} frames but atlas has {columns} columns")

        durations = state_payload.get("durationsMs")
        if not isinstance(durations, list) or len(durations) != frame_count:
            fail(f"{state} must have one duration per frame")
        for duration in durations:
            if not isinstance(duration, int) or duration <= 0:
                fail(f"{state} durationsMs values must be positive integers")

    return contract


def swift_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def swift_duration(milliseconds: int) -> str:
    return f"{milliseconds / 1000:.3f}"


def render_swift_contract(contract: dict[str, Any]) -> str:
    atlas = contract["atlas"]
    states = contract["states"]
    lines = [
        "// Generated by scripts/validate_animation_contract.py --update from docs/pet-animation-contract.json.",
        "// Do not edit by hand.",
        "",
        "import Foundation",
        "",
        f"let cellWidth = {atlas['cellWidth']}",
        f"let cellHeight = {atlas['cellHeight']}",
        f"let atlasColumns = {atlas['columns']}",
        f"let atlasRows = {atlas['rows']}",
        "let atlasWidth = cellWidth * atlasColumns",
        "let atlasHeight = cellHeight * atlasRows",
        f"let visibleAlphaThreshold: UInt8 = {atlas['visibleAlphaThreshold']}",
        "",
        "let animationRows: [AnimationRow] = [",
    ]

    for state_payload in states:
        durations = ", ".join(swift_duration(duration) for duration in state_payload["durationsMs"])
        lines.extend(
            [
                "    .init(",
                f"        state: {swift_string(state_payload['state'])},",
                f"        row: {state_payload['row']},",
                f"        frameCount: {state_payload['frames']},",
                f"        durations: [{durations}]",
                "    ),",
            ]
        )

    lines.append("]")
    return "\n".join(lines) + "\n"


def validate_generated_swift(expected: str) -> None:
    try:
        actual = GENERATED_SWIFT_PATH.read_text(encoding="utf-8")
    except OSError as exc:
        fail(f"could not read generated Swift contract: {exc}")

    if actual != expected:
        diff = difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=str(GENERATED_SWIFT_PATH.relative_to(ROOT)),
            tofile="expected generated contract",
        )
        print("error: generated Swift animation contract is stale", file=sys.stderr)
        print("Run: python3 scripts/validate_animation_contract.py --update", file=sys.stderr)
        print("".join(diff), file=sys.stderr)
        raise SystemExit(1)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Validate or update GeneratedAnimationContract.swift from docs/pet-animation-contract.json."
    )
    parser.add_argument("--update", action="store_true", help="Rewrite the generated Swift file.")
    args = parser.parse_args()

    expected = render_swift_contract(load_contract())
    if args.update:
        GENERATED_SWIFT_PATH.write_text(expected, encoding="utf-8")
        print(f"Updated {GENERATED_SWIFT_PATH.relative_to(ROOT)}.")
        return

    validate_generated_swift(expected)
    print("Animation contract matches generated Swift runtime.")


if __name__ == "__main__":
    main()
